// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "ap-northeast-1",
    "aws_content_delivery_bucket": "myapp-20181223210234-hostingbucket",
    "aws_content_delivery_bucket_region": "ap-northeast-1",
    "aws_content_delivery_url": "http://myapp-20181223210234-hostingbucket.s3-website-ap-northeast-1.amazonaws.com",
    "aws_cognito_identity_pool_id": "ap-northeast-1:dae74014-e4ab-4b54-96e6-215924016c63",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_agcNWEBO1",
    "aws_user_pools_web_client_id": "7m8o584qorngm1dop73o754ah5"
};


export default awsmobile;
